### ISSUE TITLE
I dont know how to use this, i have 1 iq

### ISSUE THREAD

**Issue by Enzogaming59430** [RickoNoNo3/react-winbox#11]
Im new in react and trying to make this work

What should i do

__________________________
### _**EDIT : I FINNALY MADE IT WORK BUT NOT PROPRELY, VERTICAL RESIZING MAKES THE WINDOW DISAPEARS, THE HIDE AND RESIZE BUTTON IS BROKEN AND CAN ONLY MOVE THE WINDOW HORISONTALY**_

```import "./App.css"
import React from 'react';
import WinBox from 'react-winbox';

const app = () => {
  
  return(
<WinBox
  width={this.state.boxWidth ?? 500}
  height={300}
  x="center"
  y={30}
  noClose={this.state.inEditing}>
  <div>
    
    <h1>Hello, WinBox!</h1>
    <MyComponent myProps={1} onChange={this.handleChange}/>
  </div>
</WinBox>
)
}

export default app; ``````

**Comment by RickoNoNo3** [comment]
There is a note aimed at this situation. See https://github.com/RickoNoNo3/react-winbox#usage

> To use WinBox, ensure the document body has an initial non-zero height, e.g. 100vh.

Maybe it's not so striking yet, I'll try to make it more clear. Thank you.

**Comment by RickoNoNo3** [comment]
#12
