### ISSUE TITLE
How can i make the top limit relative to the scroll?

### ISSUE THREAD

**Issue by jarrisoncano** [RickoNoNo3/react-winbox#25]
Im trying to create a top limit to my winbox's components for avoid render the winbox in front of the ribbon but i need that when the user scroll and the ribbon disappear, the top limit change. Basically i need a functionality like position: sticky.

Im trying to fix that listening the scroll of the page and change the state that have the top limit when the navbar is on the screen, but doesnt work :l

```
const handleScroll = () => {
	if (window.pageYOffset <= 70) setTop(navbarHeight)
	else setTop(48)
}

window.addEventListener('scroll', handleScroll)
```

On initial render the top function correctly:
![image](https://user-images.githubusercontent.com/62910118/216621332-3a3b0b6c-c487-4f14-a888-353c7c9e6831.png)

But when i scroll, move the element and go back to the top, the limit dont work 
![image](https://user-images.githubusercontent.com/62910118/216621377-f148e780-2ecd-43b1-b2b4-e290c6062057.png)

Looks like the component doesnt make update the internal value each time that the top state change.

**Comment by jarrisoncano** [comment]
I fix it modifying the styles of the winbox element, may be its to the better solution for the performance but for the moment function for me

![image](https://user-images.githubusercontent.com/62910118/216628341-14f3b4ca-936c-41c5-9e3b-939ec186f8e5.png)

**Comment by RickoNoNo3** [comment]
Your trying is valuable.

You may also try to set the `y` prop which determines the position of the winbox, to replace `style.top`. But the current is nice as well doesn't it?

And go further, I guess the top has indeed been changed, but the position of winbox was never refreshed. A `move()` after set top may solve the problem. This has been integrated into the code and would run automatically before, but seems not working now, I'll check off it.

Anyway, thank you for your report
