### ISSUE TITLE
Create a directory with example?

### ISSUE THREAD

**Issue by JSchmidt63** [RickoNoNo3/react-winbox#28]
Hi,
this a great component.
But is it easier to try some some example:
1. demo: https://react-winbox.vercel.app/ with full source
2. https://github.com/RickoNoNo3/react-winbox/blob/main/demo.jpg with full source

Cheers :-) 👍

**Comment by RickoNoNo3** [comment]
Thank you for your proposal. The source code of demo is indeed placed in: https://github.com/RickoNoNo3/react-winbox-demo

Most of the key codes have been given on the web page. So I am not sure if this repo can help you, but I wish. THX
