### ISSUE TITLE
Not working with react-query 

### ISSUE THREAD

**Issue by kobe651jp** [RickoNoNo3/react-winbox#4]
When I try to use react-winbox with react-query .Getting errors.

![Screenshot from 2022-05-18 22-53-36](https://user-images.githubusercontent.com/44263972/169057287-a9b598db-7e73-4d5c-a15e-7b566040f48d.png)

My guess is react-winbox not working with react context.

**from** 
https://react-query.tanstack.com/overview#enough-talk-show-me-some-code-already

![Screenshot from 2022-05-18 22-47-51](https://user-images.githubusercontent.com/44263972/169056059-df231a6a-49fb-48ce-a83d-b5804413cd27.png)

**to**
![Screenshot from 2022-05-18 22-51-09](https://user-images.githubusercontent.com/44263972/169056472-dcbb3c7a-f0b5-4cfa-8c71-bc11c11923fa.png)

**Comment by RickoNoNo3** [comment]
Thanks for your find. I will try to study and solve it. Would you mind to test a pure React Context enviroment to locate the problem? I'll check it too.

**Comment by kobe651jp** [comment]
I'm tried to use winbox with context and redux.Below is my code.

problem is the context and redux-store can't update main store.
I have no solution yet.

```
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import WinBox from 'winbox/src/js/winbox';
import 'winbox/dist/css/winbox.min.css';
import { ConnectedRouter } from 'connected-react-router';
import history from 'utils/history';
import { QueryClient, QueryClientProvider } from 'react-query';
import GlobalContextProvider from 'context/globalContext';

const WinPanel = (reduxStore, children) => {
  // 同じIDのwinboxで、複数Openしないように。
  const node = document.getElementById('page-footer-winbox-00');
  const win = new WinBox('online manual', {
    id: 'page-footer-winbox-00',
    width: 480,
    x: 'right',
    right: 0,
    top: 0,
    bottom: 0,
    border: 'none',
    background:
      'linear-gradient(90deg, var(--theme-primary-900) 0%, rgba(85,129,231,1) 56%, rgba(8,199,237,1) 100%)',
    class: 'z-index-9999 bg-gray-200 h-100',
    mount: node,
  });

  const queryClient = new QueryClient({
    defaultOptions: {
      queries: {
        refetchOnWindowFocus: false,
      },
    },
  });

  // Providerで囲むと、RootComponentの中で、useActionが使える。redux-storeにアクセス可能。
  ReactDOM.render(
    <Provider store={reduxStore}>
      <ConnectedRouter history={history}>
        <QueryClientProvider client={queryClient}>
          <GlobalContextProvider>{children}</GlobalContextProvider>
        </QueryClientProvider>
      </ConnectedRouter>
    </Provider>,
    win.body,
  );
};

export default WinPanel;
```

**Comment by RickoNoNo3** [comment]
It's truly a context problem. The new children in WinBox created by `ReactDOM.render()` do not exist in the component node tree following App Component. To solve this, I'm trying to restructure the render logic by using [Portals](https://17.reactjs.org/docs/portals.html) rather than render root. From the description of the document, this is a feasible solution. Thanks for your reporting!

**Comment by kobe651jp** [comment]
It's working very well.

Thanks
